### ISSUE TITLE
feat: 获取准确的舰长陪伴天数

### ISSUE THREAD

**Issue by skyatgit** [yjl9903/fetch-captain#161]
### Clear and concise description of the problem

目前显示的舰长陪伴天数不准确
可能是因为此项目 https://github.com/yjl9903/fetch-captain 中使用的接口没有返回陪伴天数的原因
导致作者无法在data的csv中收集每个人的陪伴天数
现在有新的接口可以返回每个人的陪伴天数，但本人不太懂前端技术，希望作者可以适配一下，使显示的内容更加准确

### Suggested solution

此接口
https://api.live.bilibili.com/xlive/app-room/v2/guardTab/topList?roomid=26887365&page=2&ruid=3493110847900630
的accompany字段表示的陪伴天数

**Comment by yjl9903** [comment]
Done.

I will create another issues to update Miki-Captain template repo.
